apiVersion: v1
kind: Pod 
metadata:
  name: pod1
spec:
  containers:
  - image: nginx:alpine
    name: pod1-cont
    env:
    - name: TREE1
      valueFrom:
        configMapKeyRef:
        - name: trauerweide
          key: tree
    volumeMounts:
    - mountPath: /etc/birke
      name: birke 
  volumes:
  - name: birke
    configMap:
      name: birke
    

































